/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDaemonHook,
  IDaemonHookInterface,
} from "../../contracts/IDaemonHook";

const _abi = [
  {
    inputs: [],
    name: "MAX_LP_FEE",
    outputs: [
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_MEV_LP_FEE",
    outputs: [
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_MEV_MODULE_DELAY",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PROTOCOL_FEE_NUMERATOR",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "baseToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "builderRewardDistributor",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeSplitter",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "PoolId",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "getPoolConfig",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "feyIsToken0",
            type: "bool",
          },
          {
            internalType: "address",
            name: "locker",
            type: "address",
          },
          {
            internalType: "address",
            name: "mevModule",
            type: "address",
          },
          {
            internalType: "bool",
            name: "mevModuleEnabled",
            type: "bool",
          },
          {
            internalType: "uint24",
            name: "feyFee",
            type: "uint24",
          },
          {
            internalType: "uint24",
            name: "pairedFee",
            type: "uint24",
          },
          {
            internalType: "address",
            name: "poolExtension",
            type: "address",
          },
          {
            internalType: "bool",
            name: "poolExtensionSetup",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "poolCreationTimestamp",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "tokenAdmin",
            type: "address",
          },
        ],
        internalType: "struct IDaemonHook.PoolConfig",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "PoolId",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "getTokenAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "fey",
        type: "address",
      },
      {
        internalType: "address",
        name: "pairedToken",
        type: "address",
      },
      {
        internalType: "int24",
        name: "tickIfToken0IsFey",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "tickSpacing",
        type: "int24",
      },
      {
        internalType: "address",
        name: "locker",
        type: "address",
      },
      {
        internalType: "address",
        name: "mevModule",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "poolData",
        type: "bytes",
      },
    ],
    name: "initializePool",
    outputs: [
      {
        components: [
          {
            internalType: "Currency",
            name: "currency0",
            type: "address",
          },
          {
            internalType: "Currency",
            name: "currency1",
            type: "address",
          },
          {
            internalType: "uint24",
            name: "fee",
            type: "uint24",
          },
          {
            internalType: "int24",
            name: "tickSpacing",
            type: "int24",
          },
          {
            internalType: "contract IHooks",
            name: "hooks",
            type: "address",
          },
        ],
        internalType: "struct PoolKey",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "PoolId",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "poolExists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "PoolId",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "poolTokenAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "protocolFee",
    outputs: [
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "weth",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDaemonHook__factory {
  static readonly abi = _abi;
  static createInterface(): IDaemonHookInterface {
    return new Interface(_abi) as IDaemonHookInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDaemonHook {
    return new Contract(address, _abi, runner) as unknown as IDaemonHook;
  }
}
