/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IContributionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateDecayedScore"
      | "getContributorHistory"
      | "getContributorTotalScore"
      | "recordContribution"
      | "verifyContribution"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateDecayedScore",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorTotalScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordContribution",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyContribution",
    values: [BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateDecayedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyContribution",
    data: BytesLike
  ): Result;
}

export interface IContributionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IContributionRegistry;
  waitForDeployment(): Promise<this>;

  interface: IContributionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateDecayedScore: TypedContractMethod<
    [baseScore: BigNumberish, timestamp: BigNumberish],
    [bigint],
    "view"
  >;

  getContributorHistory: TypedContractMethod<
    [contributor: AddressLike],
    [
      [string[], bigint[], bigint[]] & {
        hashes: string[];
        scores: bigint[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;

  getContributorTotalScore: TypedContractMethod<
    [contributor: AddressLike],
    [bigint],
    "view"
  >;

  recordContribution: TypedContractMethod<
    [contributor: AddressLike, prUrl: string, contributionType: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyContribution: TypedContractMethod<
    [contributionHash: BytesLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateDecayedScore"
  ): TypedContractMethod<
    [baseScore: BigNumberish, timestamp: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContributorHistory"
  ): TypedContractMethod<
    [contributor: AddressLike],
    [
      [string[], bigint[], bigint[]] & {
        hashes: string[];
        scores: bigint[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContributorTotalScore"
  ): TypedContractMethod<[contributor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordContribution"
  ): TypedContractMethod<
    [contributor: AddressLike, prUrl: string, contributionType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyContribution"
  ): TypedContractMethod<
    [contributionHash: BytesLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
