/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BuilderRewardDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "BUILDER_CUT_BPS"
      | "DECAY_GRACE_PERIOD_DAYS"
      | "DECAY_RATE_BPS"
      | "EPOCH_DURATION"
      | "MIN_SCORE_FLOOR"
      | "SCORE_PRECISION"
      | "claimRewards"
      | "contributionRegistry"
      | "currentEpoch"
      | "daemonToken"
      | "dailyDistributions"
      | "depositRewards"
      | "distributeDailyRewards"
      | "emergencyWithdraw"
      | "getAvailableRewards"
      | "getContributorScore"
      | "lastClaimEpoch"
      | "owner"
      | "pendingRewards"
      | "registerContribution"
      | "renounceOwnership"
      | "rewardToken"
      | "rewardTokenSplitBps"
      | "setContributionRegistry"
      | "setDaemonToken"
      | "setRewardToken"
      | "setRewardTokenSplit"
      | "transferOwnership"
      | "updateContributorScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContributionRegistered"
      | "ContributionRegistryUpdated"
      | "DaemonTokenUpdated"
      | "DailyRewardsDistributed"
      | "OwnershipTransferred"
      | "RewardTokenSplitUpdated"
      | "RewardTokenUpdated"
      | "RewardsClaimed"
      | "RewardsDeposited"
      | "ScoreUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BUILDER_CUT_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DECAY_GRACE_PERIOD_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DECAY_RATE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EPOCH_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_SCORE_FLOOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCORE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributionRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "daemonToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyDistributions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositRewards",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeDailyRewards",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastClaimEpoch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerContribution",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardTokenSplitBps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setContributionRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDaemonToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardTokenSplit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContributorScore",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BUILDER_CUT_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DECAY_GRACE_PERIOD_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DECAY_RATE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EPOCH_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_SCORE_FLOOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCORE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributionRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "daemonToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyDistributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeDailyRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastClaimEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardTokenSplitBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContributionRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDaemonToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardTokenSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContributorScore",
    data: BytesLike
  ): Result;
}

export namespace ContributionRegisteredEvent {
  export type InputTuple = [
    contributor: AddressLike,
    score: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contributor: string,
    score: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    contributor: string;
    score: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionRegistryUpdatedEvent {
  export type InputTuple = [oldRegistry: AddressLike, newRegistry: AddressLike];
  export type OutputTuple = [oldRegistry: string, newRegistry: string];
  export interface OutputObject {
    oldRegistry: string;
    newRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DaemonTokenUpdatedEvent {
  export type InputTuple = [daemonToken: AddressLike];
  export type OutputTuple = [daemonToken: string];
  export interface OutputObject {
    daemonToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyRewardsDistributedEvent {
  export type InputTuple = [
    epoch: BigNumberish,
    totalScore: BigNumberish,
    totalRewards: BigNumberish
  ];
  export type OutputTuple = [
    epoch: bigint,
    totalScore: bigint,
    totalRewards: bigint
  ];
  export interface OutputObject {
    epoch: bigint;
    totalScore: bigint;
    totalRewards: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardTokenSplitUpdatedEvent {
  export type InputTuple = [token: AddressLike, wethSplitBps: BigNumberish];
  export type OutputTuple = [token: string, wethSplitBps: bigint];
  export interface OutputObject {
    token: string;
    wethSplitBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardTokenUpdatedEvent {
  export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
  export type OutputTuple = [oldToken: string, newToken: string];
  export interface OutputObject {
    oldToken: string;
    newToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [
    contributor: AddressLike,
    amount: BigNumberish,
    epoch: BigNumberish
  ];
  export type OutputTuple = [
    contributor: string,
    amount: bigint,
    epoch: bigint
  ];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDepositedEvent {
  export type InputTuple = [depositor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [depositor: string, amount: bigint];
  export interface OutputObject {
    depositor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreUpdatedEvent {
  export type InputTuple = [
    contributor: AddressLike,
    scoreDelta: BigNumberish,
    newScore: BigNumberish
  ];
  export type OutputTuple = [
    contributor: string,
    scoreDelta: bigint,
    newScore: bigint
  ];
  export interface OutputObject {
    contributor: string;
    scoreDelta: bigint;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BuilderRewardDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): BuilderRewardDistributor;
  waitForDeployment(): Promise<this>;

  interface: BuilderRewardDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  BUILDER_CUT_BPS: TypedContractMethod<[], [bigint], "view">;

  DECAY_GRACE_PERIOD_DAYS: TypedContractMethod<[], [bigint], "view">;

  DECAY_RATE_BPS: TypedContractMethod<[], [bigint], "view">;

  EPOCH_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_SCORE_FLOOR: TypedContractMethod<[], [bigint], "view">;

  SCORE_PRECISION: TypedContractMethod<[], [bigint], "view">;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  contributionRegistry: TypedContractMethod<[], [string], "view">;

  currentEpoch: TypedContractMethod<[], [bigint], "view">;

  daemonToken: TypedContractMethod<[], [string], "view">;

  dailyDistributions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalScore: bigint;
        totalRewards: bigint;
        timestamp: bigint;
        distributed: boolean;
      }
    ],
    "view"
  >;

  depositRewards: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeDailyRewards: TypedContractMethod<
    [contributors: AddressLike[], scores: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAvailableRewards: TypedContractMethod<
    [contributor: AddressLike],
    [bigint],
    "view"
  >;

  getContributorScore: TypedContractMethod<
    [contributor: AddressLike, timestamp: BigNumberish],
    [bigint],
    "view"
  >;

  lastClaimEpoch: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  registerContribution: TypedContractMethod<
    [contributor: AddressLike, score: BigNumberish, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardToken: TypedContractMethod<[], [string], "view">;

  rewardTokenSplitBps: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  setContributionRegistry: TypedContractMethod<
    [newRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  setDaemonToken: TypedContractMethod<
    [_daemonToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setRewardToken: TypedContractMethod<
    [newToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setRewardTokenSplit: TypedContractMethod<
    [token: AddressLike, wethSplitBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateContributorScore: TypedContractMethod<
    [contributor: AddressLike, scoreDelta: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BUILDER_CUT_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DECAY_GRACE_PERIOD_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DECAY_RATE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EPOCH_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_SCORE_FLOOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCORE_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contributionRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "daemonToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dailyDistributions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalScore: bigint;
        totalRewards: bigint;
        timestamp: bigint;
        distributed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositRewards"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeDailyRewards"
  ): TypedContractMethod<
    [contributors: AddressLike[], scores: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAvailableRewards"
  ): TypedContractMethod<[contributor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContributorScore"
  ): TypedContractMethod<
    [contributor: AddressLike, timestamp: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastClaimEpoch"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingRewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerContribution"
  ): TypedContractMethod<
    [contributor: AddressLike, score: BigNumberish, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rewardTokenSplitBps"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setContributionRegistry"
  ): TypedContractMethod<[newRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDaemonToken"
  ): TypedContractMethod<[_daemonToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRewardToken"
  ): TypedContractMethod<[newToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRewardTokenSplit"
  ): TypedContractMethod<
    [token: AddressLike, wethSplitBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateContributorScore"
  ): TypedContractMethod<
    [contributor: AddressLike, scoreDelta: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ContributionRegistered"
  ): TypedContractEvent<
    ContributionRegisteredEvent.InputTuple,
    ContributionRegisteredEvent.OutputTuple,
    ContributionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ContributionRegistryUpdated"
  ): TypedContractEvent<
    ContributionRegistryUpdatedEvent.InputTuple,
    ContributionRegistryUpdatedEvent.OutputTuple,
    ContributionRegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DaemonTokenUpdated"
  ): TypedContractEvent<
    DaemonTokenUpdatedEvent.InputTuple,
    DaemonTokenUpdatedEvent.OutputTuple,
    DaemonTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DailyRewardsDistributed"
  ): TypedContractEvent<
    DailyRewardsDistributedEvent.InputTuple,
    DailyRewardsDistributedEvent.OutputTuple,
    DailyRewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardTokenSplitUpdated"
  ): TypedContractEvent<
    RewardTokenSplitUpdatedEvent.InputTuple,
    RewardTokenSplitUpdatedEvent.OutputTuple,
    RewardTokenSplitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardTokenUpdated"
  ): TypedContractEvent<
    RewardTokenUpdatedEvent.InputTuple,
    RewardTokenUpdatedEvent.OutputTuple,
    RewardTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDeposited"
  ): TypedContractEvent<
    RewardsDepositedEvent.InputTuple,
    RewardsDepositedEvent.OutputTuple,
    RewardsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreUpdated"
  ): TypedContractEvent<
    ScoreUpdatedEvent.InputTuple,
    ScoreUpdatedEvent.OutputTuple,
    ScoreUpdatedEvent.OutputObject
  >;

  filters: {
    "ContributionRegistered(address,uint256,uint256)": TypedContractEvent<
      ContributionRegisteredEvent.InputTuple,
      ContributionRegisteredEvent.OutputTuple,
      ContributionRegisteredEvent.OutputObject
    >;
    ContributionRegistered: TypedContractEvent<
      ContributionRegisteredEvent.InputTuple,
      ContributionRegisteredEvent.OutputTuple,
      ContributionRegisteredEvent.OutputObject
    >;

    "ContributionRegistryUpdated(address,address)": TypedContractEvent<
      ContributionRegistryUpdatedEvent.InputTuple,
      ContributionRegistryUpdatedEvent.OutputTuple,
      ContributionRegistryUpdatedEvent.OutputObject
    >;
    ContributionRegistryUpdated: TypedContractEvent<
      ContributionRegistryUpdatedEvent.InputTuple,
      ContributionRegistryUpdatedEvent.OutputTuple,
      ContributionRegistryUpdatedEvent.OutputObject
    >;

    "DaemonTokenUpdated(address)": TypedContractEvent<
      DaemonTokenUpdatedEvent.InputTuple,
      DaemonTokenUpdatedEvent.OutputTuple,
      DaemonTokenUpdatedEvent.OutputObject
    >;
    DaemonTokenUpdated: TypedContractEvent<
      DaemonTokenUpdatedEvent.InputTuple,
      DaemonTokenUpdatedEvent.OutputTuple,
      DaemonTokenUpdatedEvent.OutputObject
    >;

    "DailyRewardsDistributed(uint256,uint256,uint256)": TypedContractEvent<
      DailyRewardsDistributedEvent.InputTuple,
      DailyRewardsDistributedEvent.OutputTuple,
      DailyRewardsDistributedEvent.OutputObject
    >;
    DailyRewardsDistributed: TypedContractEvent<
      DailyRewardsDistributedEvent.InputTuple,
      DailyRewardsDistributedEvent.OutputTuple,
      DailyRewardsDistributedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardTokenSplitUpdated(address,uint256)": TypedContractEvent<
      RewardTokenSplitUpdatedEvent.InputTuple,
      RewardTokenSplitUpdatedEvent.OutputTuple,
      RewardTokenSplitUpdatedEvent.OutputObject
    >;
    RewardTokenSplitUpdated: TypedContractEvent<
      RewardTokenSplitUpdatedEvent.InputTuple,
      RewardTokenSplitUpdatedEvent.OutputTuple,
      RewardTokenSplitUpdatedEvent.OutputObject
    >;

    "RewardTokenUpdated(address,address)": TypedContractEvent<
      RewardTokenUpdatedEvent.InputTuple,
      RewardTokenUpdatedEvent.OutputTuple,
      RewardTokenUpdatedEvent.OutputObject
    >;
    RewardTokenUpdated: TypedContractEvent<
      RewardTokenUpdatedEvent.InputTuple,
      RewardTokenUpdatedEvent.OutputTuple,
      RewardTokenUpdatedEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "RewardsDeposited(address,uint256)": TypedContractEvent<
      RewardsDepositedEvent.InputTuple,
      RewardsDepositedEvent.OutputTuple,
      RewardsDepositedEvent.OutputObject
    >;
    RewardsDeposited: TypedContractEvent<
      RewardsDepositedEvent.InputTuple,
      RewardsDepositedEvent.OutputTuple,
      RewardsDepositedEvent.OutputObject
    >;

    "ScoreUpdated(address,int256,uint256)": TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
    ScoreUpdated: TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
  };
}
