/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ContributionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_SCORE_BUGFIX"
      | "BASE_SCORE_CODE"
      | "BASE_SCORE_DOCS"
      | "BASE_SCORE_FEATURE"
      | "BASE_SCORE_REFACTOR"
      | "BASE_SCORE_SDK"
      | "BASE_SCORE_TESTS"
      | "DECAY_GRACE_PERIOD"
      | "DECAY_RATE_BPS"
      | "MIN_SCORE_FLOOR"
      | "SCORE_PRECISION"
      | "authorizedRecorders"
      | "builderRewardDistributor"
      | "calculateDecayedScore"
      | "contributionWeights"
      | "contributions"
      | "contributorContributions"
      | "contributorInfo"
      | "getBaseScore"
      | "getContributorHistory"
      | "getContributorTotalScore"
      | "owner"
      | "recordContribution"
      | "renounceOwnership"
      | "setAuthorizedRecorder"
      | "setBuilderRewardDistributor"
      | "setContributionWeight"
      | "transferOwnership"
      | "verifyContribution"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizedRecorderUpdated"
      | "BuilderRewardDistributorUpdated"
      | "ContributionRecorded"
      | "ContributionVerified"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_SCORE_BUGFIX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_SCORE_CODE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_SCORE_DOCS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_SCORE_FEATURE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_SCORE_REFACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_SCORE_SDK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_SCORE_TESTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DECAY_GRACE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DECAY_RATE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_SCORE_FLOOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCORE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedRecorders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "builderRewardDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateDecayedScore",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributionWeights",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorContributions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBaseScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorTotalScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordContribution",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedRecorder",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBuilderRewardDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setContributionWeight",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyContribution",
    values: [BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_SCORE_BUGFIX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_SCORE_CODE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_SCORE_DOCS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_SCORE_FEATURE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_SCORE_REFACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_SCORE_SDK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_SCORE_TESTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DECAY_GRACE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DECAY_RATE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_SCORE_FLOOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCORE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedRecorders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "builderRewardDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateDecayedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributionWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBaseScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedRecorder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBuilderRewardDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContributionWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyContribution",
    data: BytesLike
  ): Result;
}

export namespace AuthorizedRecorderUpdatedEvent {
  export type InputTuple = [recorder: AddressLike, authorized: boolean];
  export type OutputTuple = [recorder: string, authorized: boolean];
  export interface OutputObject {
    recorder: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuilderRewardDistributorUpdatedEvent {
  export type InputTuple = [
    oldDistributor: AddressLike,
    newDistributor: AddressLike
  ];
  export type OutputTuple = [oldDistributor: string, newDistributor: string];
  export interface OutputObject {
    oldDistributor: string;
    newDistributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionRecordedEvent {
  export type InputTuple = [
    contributor: AddressLike,
    contributionHash: BytesLike,
    prUrl: string,
    score: BigNumberish,
    contributionType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contributor: string,
    contributionHash: string,
    prUrl: string,
    score: bigint,
    contributionType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    contributor: string;
    contributionHash: string;
    prUrl: string;
    score: bigint;
    contributionType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionVerifiedEvent {
  export type InputTuple = [contributionHash: BytesLike, verified: boolean];
  export type OutputTuple = [contributionHash: string, verified: boolean];
  export interface OutputObject {
    contributionHash: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ContributionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ContributionRegistry;
  waitForDeployment(): Promise<this>;

  interface: ContributionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_SCORE_BUGFIX: TypedContractMethod<[], [bigint], "view">;

  BASE_SCORE_CODE: TypedContractMethod<[], [bigint], "view">;

  BASE_SCORE_DOCS: TypedContractMethod<[], [bigint], "view">;

  BASE_SCORE_FEATURE: TypedContractMethod<[], [bigint], "view">;

  BASE_SCORE_REFACTOR: TypedContractMethod<[], [bigint], "view">;

  BASE_SCORE_SDK: TypedContractMethod<[], [bigint], "view">;

  BASE_SCORE_TESTS: TypedContractMethod<[], [bigint], "view">;

  DECAY_GRACE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  DECAY_RATE_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_SCORE_FLOOR: TypedContractMethod<[], [bigint], "view">;

  SCORE_PRECISION: TypedContractMethod<[], [bigint], "view">;

  authorizedRecorders: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  builderRewardDistributor: TypedContractMethod<[], [string], "view">;

  calculateDecayedScore: TypedContractMethod<
    [baseScore: BigNumberish, timestamp: BigNumberish],
    [bigint],
    "view"
  >;

  contributionWeights: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  contributions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, boolean, string] & {
        contributor: string;
        prUrl: string;
        score: bigint;
        timestamp: bigint;
        contributionType: bigint;
        verified: boolean;
        contributionHash: string;
      }
    ],
    "view"
  >;

  contributorContributions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  contributorInfo: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        contributor: string;
        totalScore: bigint;
        lastContributionTimestamp: bigint;
        contributionCount: bigint;
      }
    ],
    "view"
  >;

  getBaseScore: TypedContractMethod<
    [contributionType: BigNumberish],
    [bigint],
    "view"
  >;

  getContributorHistory: TypedContractMethod<
    [contributor: AddressLike],
    [
      [string[], bigint[], bigint[]] & {
        hashes: string[];
        scores: bigint[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;

  getContributorTotalScore: TypedContractMethod<
    [contributor: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordContribution: TypedContractMethod<
    [contributor: AddressLike, prUrl: string, contributionType: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedRecorder: TypedContractMethod<
    [recorder: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setBuilderRewardDistributor: TypedContractMethod<
    [newDistributor: AddressLike],
    [void],
    "nonpayable"
  >;

  setContributionWeight: TypedContractMethod<
    [contributionType: BigNumberish, weight: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyContribution: TypedContractMethod<
    [contributionHash: BytesLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_SCORE_BUGFIX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_SCORE_CODE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_SCORE_DOCS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_SCORE_FEATURE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_SCORE_REFACTOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_SCORE_SDK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_SCORE_TESTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DECAY_GRACE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DECAY_RATE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_SCORE_FLOOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCORE_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizedRecorders"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "builderRewardDistributor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculateDecayedScore"
  ): TypedContractMethod<
    [baseScore: BigNumberish, timestamp: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "contributionWeights"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, boolean, string] & {
        contributor: string;
        prUrl: string;
        score: bigint;
        timestamp: bigint;
        contributionType: bigint;
        verified: boolean;
        contributionHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "contributorContributions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "contributorInfo"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        contributor: string;
        totalScore: bigint;
        lastContributionTimestamp: bigint;
        contributionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBaseScore"
  ): TypedContractMethod<[contributionType: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContributorHistory"
  ): TypedContractMethod<
    [contributor: AddressLike],
    [
      [string[], bigint[], bigint[]] & {
        hashes: string[];
        scores: bigint[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContributorTotalScore"
  ): TypedContractMethod<[contributor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordContribution"
  ): TypedContractMethod<
    [contributor: AddressLike, prUrl: string, contributionType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedRecorder"
  ): TypedContractMethod<
    [recorder: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBuilderRewardDistributor"
  ): TypedContractMethod<[newDistributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setContributionWeight"
  ): TypedContractMethod<
    [contributionType: BigNumberish, weight: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyContribution"
  ): TypedContractMethod<
    [contributionHash: BytesLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuthorizedRecorderUpdated"
  ): TypedContractEvent<
    AuthorizedRecorderUpdatedEvent.InputTuple,
    AuthorizedRecorderUpdatedEvent.OutputTuple,
    AuthorizedRecorderUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BuilderRewardDistributorUpdated"
  ): TypedContractEvent<
    BuilderRewardDistributorUpdatedEvent.InputTuple,
    BuilderRewardDistributorUpdatedEvent.OutputTuple,
    BuilderRewardDistributorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionRecorded"
  ): TypedContractEvent<
    ContributionRecordedEvent.InputTuple,
    ContributionRecordedEvent.OutputTuple,
    ContributionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionVerified"
  ): TypedContractEvent<
    ContributionVerifiedEvent.InputTuple,
    ContributionVerifiedEvent.OutputTuple,
    ContributionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AuthorizedRecorderUpdated(address,bool)": TypedContractEvent<
      AuthorizedRecorderUpdatedEvent.InputTuple,
      AuthorizedRecorderUpdatedEvent.OutputTuple,
      AuthorizedRecorderUpdatedEvent.OutputObject
    >;
    AuthorizedRecorderUpdated: TypedContractEvent<
      AuthorizedRecorderUpdatedEvent.InputTuple,
      AuthorizedRecorderUpdatedEvent.OutputTuple,
      AuthorizedRecorderUpdatedEvent.OutputObject
    >;

    "BuilderRewardDistributorUpdated(address,address)": TypedContractEvent<
      BuilderRewardDistributorUpdatedEvent.InputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputObject
    >;
    BuilderRewardDistributorUpdated: TypedContractEvent<
      BuilderRewardDistributorUpdatedEvent.InputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputObject
    >;

    "ContributionRecorded(address,bytes32,string,uint256,uint8,uint256)": TypedContractEvent<
      ContributionRecordedEvent.InputTuple,
      ContributionRecordedEvent.OutputTuple,
      ContributionRecordedEvent.OutputObject
    >;
    ContributionRecorded: TypedContractEvent<
      ContributionRecordedEvent.InputTuple,
      ContributionRecordedEvent.OutputTuple,
      ContributionRecordedEvent.OutputObject
    >;

    "ContributionVerified(bytes32,bool)": TypedContractEvent<
      ContributionVerifiedEvent.InputTuple,
      ContributionVerifiedEvent.OutputTuple,
      ContributionVerifiedEvent.OutputObject
    >;
    ContributionVerified: TypedContractEvent<
      ContributionVerifiedEvent.InputTuple,
      ContributionVerifiedEvent.OutputTuple,
      ContributionVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
