/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type PoolKeyStruct = {
  currency0: AddressLike;
  currency1: AddressLike;
  fee: BigNumberish;
  tickSpacing: BigNumberish;
  hooks: AddressLike;
};

export type PoolKeyStructOutput = [
  currency0: string,
  currency1: string,
  fee: bigint,
  tickSpacing: bigint,
  hooks: string
] & {
  currency0: string;
  currency1: string;
  fee: bigint;
  tickSpacing: bigint;
  hooks: string;
};

export type ModifyLiquidityParamsStruct = {
  tickLower: BigNumberish;
  tickUpper: BigNumberish;
  liquidityDelta: BigNumberish;
  salt: BytesLike;
};

export type ModifyLiquidityParamsStructOutput = [
  tickLower: bigint,
  tickUpper: bigint,
  liquidityDelta: bigint,
  salt: string
] & {
  tickLower: bigint;
  tickUpper: bigint;
  liquidityDelta: bigint;
  salt: string;
};

export type SwapParamsStruct = {
  zeroForOne: boolean;
  amountSpecified: BigNumberish;
  sqrtPriceLimitX96: BigNumberish;
};

export type SwapParamsStructOutput = [
  zeroForOne: boolean,
  amountSpecified: bigint,
  sqrtPriceLimitX96: bigint
] & { zeroForOne: boolean; amountSpecified: bigint; sqrtPriceLimitX96: bigint };

export declare namespace IDaemonHook {
  export type PoolConfigStruct = {
    feyIsToken0: boolean;
    locker: AddressLike;
    mevModule: AddressLike;
    mevModuleEnabled: boolean;
    feyFee: BigNumberish;
    pairedFee: BigNumberish;
    poolExtension: AddressLike;
    poolExtensionSetup: boolean;
    poolCreationTimestamp: BigNumberish;
    tokenAdmin: AddressLike;
  };

  export type PoolConfigStructOutput = [
    feyIsToken0: boolean,
    locker: string,
    mevModule: string,
    mevModuleEnabled: boolean,
    feyFee: bigint,
    pairedFee: bigint,
    poolExtension: string,
    poolExtensionSetup: boolean,
    poolCreationTimestamp: bigint,
    tokenAdmin: string
  ] & {
    feyIsToken0: boolean;
    locker: string;
    mevModule: string;
    mevModuleEnabled: boolean;
    feyFee: bigint;
    pairedFee: bigint;
    poolExtension: string;
    poolExtensionSetup: boolean;
    poolCreationTimestamp: bigint;
    tokenAdmin: string;
  };
}

export interface DaemonHookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_LP_FEE"
      | "MAX_MEV_LP_FEE"
      | "MAX_MEV_MODULE_DELAY"
      | "PROTOCOL_FEE_NUMERATOR"
      | "UPGRADE_INTERFACE_VERSION"
      | "afterAddLiquidity"
      | "afterDonate"
      | "afterInitialize"
      | "afterRemoveLiquidity"
      | "afterSwap"
      | "baseToken"
      | "beforeAddLiquidity"
      | "beforeDonate"
      | "beforeInitialize"
      | "beforeRemoveLiquidity"
      | "beforeSwap"
      | "builderRewardDistributor"
      | "factory"
      | "feeSplitter"
      | "getPoolConfig"
      | "getTokenAdmin"
      | "initialize"
      | "initializePool"
      | "mevModuleEnabled"
      | "owner"
      | "poolCreationTimestamp"
      | "poolExists"
      | "poolExtensionAllowlist"
      | "poolManager"
      | "poolTokenAdmin"
      | "protocolFee"
      | "proxiableUUID"
      | "renounceOwnership"
      | "setBaseToken"
      | "setBuilderRewardDistributor"
      | "setFactory"
      | "setFeeSplitter"
      | "setProtocolFee"
      | "socialNetworkFund"
      | "supportsInterface"
      | "transferOwnership"
      | "upgradeToAndCall"
      | "weth"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BuilderRewardCollected"
      | "BuilderRewardDistributorUpdated"
      | "ClaimProtocolFees"
      | "FeeSplitterUpdated"
      | "Initialized"
      | "MevModuleDisabled"
      | "OwnershipTransferred"
      | "PoolCreatedFactory"
      | "PoolInitialized"
      | "ProtocolFeeUpdated"
      | "SocialNetworkFeeCollected"
      | "SocialNetworkFundUpdated"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_LP_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_MEV_LP_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_MEV_MODULE_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_NUMERATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "afterAddLiquidity",
    values: [
      AddressLike,
      PoolKeyStruct,
      ModifyLiquidityParamsStruct,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "afterDonate",
    values: [AddressLike, PoolKeyStruct, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "afterInitialize",
    values: [AddressLike, PoolKeyStruct, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "afterRemoveLiquidity",
    values: [
      AddressLike,
      PoolKeyStruct,
      ModifyLiquidityParamsStruct,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "afterSwap",
    values: [
      AddressLike,
      PoolKeyStruct,
      SwapParamsStruct,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "baseToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "beforeAddLiquidity",
    values: [AddressLike, PoolKeyStruct, ModifyLiquidityParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeDonate",
    values: [AddressLike, PoolKeyStruct, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeInitialize",
    values: [AddressLike, PoolKeyStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeRemoveLiquidity",
    values: [AddressLike, PoolKeyStruct, ModifyLiquidityParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeSwap",
    values: [AddressLike, PoolKeyStruct, SwapParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "builderRewardDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeSplitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolConfig",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initializePool",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mevModuleEnabled",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolCreationTimestamp",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolExtensionAllowlist",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolTokenAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBuilderRewardDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeSplitter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "socialNetworkFund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;

  decodeFunctionResult(functionFragment: "MAX_LP_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_MEV_LP_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_MEV_MODULE_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_NUMERATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterAddLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterDonate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterInitialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterRemoveLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "afterSwap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "beforeAddLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeDonate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeInitialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeRemoveLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "beforeSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "builderRewardDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeSplitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mevModuleEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolCreationTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolExtensionAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolTokenAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBuilderRewardDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFactory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeSplitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "socialNetworkFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
}

export namespace BuilderRewardCollectedEvent {
  export type InputTuple = [poolId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [poolId: string, amount: bigint];
  export interface OutputObject {
    poolId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuilderRewardDistributorUpdatedEvent {
  export type InputTuple = [newDistributor: AddressLike];
  export type OutputTuple = [newDistributor: string];
  export interface OutputObject {
    newDistributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimProtocolFeesEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeSplitterUpdatedEvent {
  export type InputTuple = [newSplitter: AddressLike];
  export type OutputTuple = [newSplitter: string];
  export interface OutputObject {
    newSplitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MevModuleDisabledEvent {
  export type InputTuple = [poolId: BytesLike];
  export type OutputTuple = [poolId: string];
  export interface OutputObject {
    poolId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedFactoryEvent {
  export type InputTuple = [
    pairedToken: AddressLike,
    fey: AddressLike,
    poolId: BytesLike,
    tickIfToken0IsFey: BigNumberish,
    tickSpacing: BigNumberish,
    locker: AddressLike,
    mevModule: AddressLike
  ];
  export type OutputTuple = [
    pairedToken: string,
    fey: string,
    poolId: string,
    tickIfToken0IsFey: bigint,
    tickSpacing: bigint,
    locker: string,
    mevModule: string
  ];
  export interface OutputObject {
    pairedToken: string;
    fey: string;
    poolId: string;
    tickIfToken0IsFey: bigint;
    tickSpacing: bigint;
    locker: string;
    mevModule: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolInitializedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    tokenAdmin: AddressLike,
    locker: AddressLike
  ];
  export type OutputTuple = [
    poolId: string,
    tokenAdmin: string,
    locker: string
  ];
  export interface OutputObject {
    poolId: string;
    tokenAdmin: string;
    locker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolFeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SocialNetworkFeeCollectedEvent {
  export type InputTuple = [poolId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [poolId: string, amount: bigint];
  export interface OutputObject {
    poolId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SocialNetworkFundUpdatedEvent {
  export type InputTuple = [newFund: AddressLike];
  export type OutputTuple = [newFund: string];
  export interface OutputObject {
    newFund: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DaemonHook extends BaseContract {
  connect(runner?: ContractRunner | null): DaemonHook;
  waitForDeployment(): Promise<this>;

  interface: DaemonHookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_LP_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_MEV_LP_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_MEV_MODULE_DELAY: TypedContractMethod<[], [bigint], "view">;

  PROTOCOL_FEE_NUMERATOR: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  afterAddLiquidity: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: ModifyLiquidityParamsStruct,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;

  afterDonate: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  afterInitialize: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      sqrtPriceX96: BigNumberish,
      tick: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  afterRemoveLiquidity: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: ModifyLiquidityParamsStruct,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;

  afterSwap: TypedContractMethod<
    [
      arg0: AddressLike,
      key: PoolKeyStruct,
      arg2: SwapParamsStruct,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;

  baseToken: TypedContractMethod<[], [string], "view">;

  beforeAddLiquidity: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: ModifyLiquidityParamsStruct,
      arg3: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  beforeDonate: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  beforeInitialize: TypedContractMethod<
    [arg0: AddressLike, arg1: PoolKeyStruct, arg2: BigNumberish],
    [string],
    "nonpayable"
  >;

  beforeRemoveLiquidity: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: ModifyLiquidityParamsStruct,
      arg3: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  beforeSwap: TypedContractMethod<
    [
      arg0: AddressLike,
      key: PoolKeyStruct,
      arg2: SwapParamsStruct,
      arg3: BytesLike
    ],
    [[string, bigint, bigint]],
    "nonpayable"
  >;

  builderRewardDistributor: TypedContractMethod<[], [string], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  feeSplitter: TypedContractMethod<[], [string], "view">;

  getPoolConfig: TypedContractMethod<
    [poolId: BytesLike],
    [IDaemonHook.PoolConfigStructOutput],
    "view"
  >;

  getTokenAdmin: TypedContractMethod<[poolId: BytesLike], [string], "view">;

  initialize: TypedContractMethod<
    [
      _poolManager: AddressLike,
      _factory: AddressLike,
      _baseToken: AddressLike,
      _weth: AddressLike,
      _poolExtensionAllowlist: AddressLike,
      _builderRewardDistributor: AddressLike,
      _feeSplitter: AddressLike,
      _socialNetworkFund: AddressLike,
      _owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  initializePool: TypedContractMethod<
    [
      fey: AddressLike,
      pairedToken: AddressLike,
      tickIfToken0IsFey: BigNumberish,
      tickSpacing: BigNumberish,
      locker: AddressLike,
      mevModule: AddressLike,
      poolData: BytesLike
    ],
    [PoolKeyStructOutput],
    "nonpayable"
  >;

  mevModuleEnabled: TypedContractMethod<[poolId: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  poolCreationTimestamp: TypedContractMethod<
    [poolId: BytesLike],
    [bigint],
    "view"
  >;

  poolExists: TypedContractMethod<[poolId: BytesLike], [boolean], "view">;

  poolExtensionAllowlist: TypedContractMethod<[], [string], "view">;

  poolManager: TypedContractMethod<[], [string], "view">;

  poolTokenAdmin: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  protocolFee: TypedContractMethod<[], [bigint], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBaseToken: TypedContractMethod<
    [_baseToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setBuilderRewardDistributor: TypedContractMethod<
    [_builderRewardDistributor: AddressLike],
    [void],
    "nonpayable"
  >;

  setFactory: TypedContractMethod<
    [_factory: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeSplitter: TypedContractMethod<
    [_feeSplitter: AddressLike],
    [void],
    "nonpayable"
  >;

  setProtocolFee: TypedContractMethod<
    [_protocolFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  socialNetworkFund: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  weth: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_LP_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_MEV_LP_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_MEV_MODULE_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_FEE_NUMERATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "afterAddLiquidity"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: ModifyLiquidityParamsStruct,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterDonate"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterInitialize"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      sqrtPriceX96: BigNumberish,
      tick: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterRemoveLiquidity"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: ModifyLiquidityParamsStruct,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterSwap"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      key: PoolKeyStruct,
      arg2: SwapParamsStruct,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "baseToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "beforeAddLiquidity"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: ModifyLiquidityParamsStruct,
      arg3: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeDonate"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeInitialize"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: PoolKeyStruct, arg2: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeRemoveLiquidity"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: PoolKeyStruct,
      arg2: ModifyLiquidityParamsStruct,
      arg3: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeSwap"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      key: PoolKeyStruct,
      arg2: SwapParamsStruct,
      arg3: BytesLike
    ],
    [[string, bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "builderRewardDistributor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeSplitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolConfig"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [IDaemonHook.PoolConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenAdmin"
  ): TypedContractMethod<[poolId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _poolManager: AddressLike,
      _factory: AddressLike,
      _baseToken: AddressLike,
      _weth: AddressLike,
      _poolExtensionAllowlist: AddressLike,
      _builderRewardDistributor: AddressLike,
      _feeSplitter: AddressLike,
      _socialNetworkFund: AddressLike,
      _owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initializePool"
  ): TypedContractMethod<
    [
      fey: AddressLike,
      pairedToken: AddressLike,
      tickIfToken0IsFey: BigNumberish,
      tickSpacing: BigNumberish,
      locker: AddressLike,
      mevModule: AddressLike,
      poolData: BytesLike
    ],
    [PoolKeyStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mevModuleEnabled"
  ): TypedContractMethod<[poolId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolCreationTimestamp"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "poolExists"
  ): TypedContractMethod<[poolId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "poolExtensionAllowlist"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolTokenAdmin"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBaseToken"
  ): TypedContractMethod<[_baseToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBuilderRewardDistributor"
  ): TypedContractMethod<
    [_builderRewardDistributor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFactory"
  ): TypedContractMethod<[_factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeSplitter"
  ): TypedContractMethod<[_feeSplitter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolFee"
  ): TypedContractMethod<[_protocolFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "socialNetworkFund"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "weth"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BuilderRewardCollected"
  ): TypedContractEvent<
    BuilderRewardCollectedEvent.InputTuple,
    BuilderRewardCollectedEvent.OutputTuple,
    BuilderRewardCollectedEvent.OutputObject
  >;
  getEvent(
    key: "BuilderRewardDistributorUpdated"
  ): TypedContractEvent<
    BuilderRewardDistributorUpdatedEvent.InputTuple,
    BuilderRewardDistributorUpdatedEvent.OutputTuple,
    BuilderRewardDistributorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimProtocolFees"
  ): TypedContractEvent<
    ClaimProtocolFeesEvent.InputTuple,
    ClaimProtocolFeesEvent.OutputTuple,
    ClaimProtocolFeesEvent.OutputObject
  >;
  getEvent(
    key: "FeeSplitterUpdated"
  ): TypedContractEvent<
    FeeSplitterUpdatedEvent.InputTuple,
    FeeSplitterUpdatedEvent.OutputTuple,
    FeeSplitterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MevModuleDisabled"
  ): TypedContractEvent<
    MevModuleDisabledEvent.InputTuple,
    MevModuleDisabledEvent.OutputTuple,
    MevModuleDisabledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreatedFactory"
  ): TypedContractEvent<
    PoolCreatedFactoryEvent.InputTuple,
    PoolCreatedFactoryEvent.OutputTuple,
    PoolCreatedFactoryEvent.OutputObject
  >;
  getEvent(
    key: "PoolInitialized"
  ): TypedContractEvent<
    PoolInitializedEvent.InputTuple,
    PoolInitializedEvent.OutputTuple,
    PoolInitializedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolFeeUpdated"
  ): TypedContractEvent<
    ProtocolFeeUpdatedEvent.InputTuple,
    ProtocolFeeUpdatedEvent.OutputTuple,
    ProtocolFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SocialNetworkFeeCollected"
  ): TypedContractEvent<
    SocialNetworkFeeCollectedEvent.InputTuple,
    SocialNetworkFeeCollectedEvent.OutputTuple,
    SocialNetworkFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "SocialNetworkFundUpdated"
  ): TypedContractEvent<
    SocialNetworkFundUpdatedEvent.InputTuple,
    SocialNetworkFundUpdatedEvent.OutputTuple,
    SocialNetworkFundUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "BuilderRewardCollected(bytes32,uint256)": TypedContractEvent<
      BuilderRewardCollectedEvent.InputTuple,
      BuilderRewardCollectedEvent.OutputTuple,
      BuilderRewardCollectedEvent.OutputObject
    >;
    BuilderRewardCollected: TypedContractEvent<
      BuilderRewardCollectedEvent.InputTuple,
      BuilderRewardCollectedEvent.OutputTuple,
      BuilderRewardCollectedEvent.OutputObject
    >;

    "BuilderRewardDistributorUpdated(address)": TypedContractEvent<
      BuilderRewardDistributorUpdatedEvent.InputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputObject
    >;
    BuilderRewardDistributorUpdated: TypedContractEvent<
      BuilderRewardDistributorUpdatedEvent.InputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputObject
    >;

    "ClaimProtocolFees(address,uint256)": TypedContractEvent<
      ClaimProtocolFeesEvent.InputTuple,
      ClaimProtocolFeesEvent.OutputTuple,
      ClaimProtocolFeesEvent.OutputObject
    >;
    ClaimProtocolFees: TypedContractEvent<
      ClaimProtocolFeesEvent.InputTuple,
      ClaimProtocolFeesEvent.OutputTuple,
      ClaimProtocolFeesEvent.OutputObject
    >;

    "FeeSplitterUpdated(address)": TypedContractEvent<
      FeeSplitterUpdatedEvent.InputTuple,
      FeeSplitterUpdatedEvent.OutputTuple,
      FeeSplitterUpdatedEvent.OutputObject
    >;
    FeeSplitterUpdated: TypedContractEvent<
      FeeSplitterUpdatedEvent.InputTuple,
      FeeSplitterUpdatedEvent.OutputTuple,
      FeeSplitterUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MevModuleDisabled(bytes32)": TypedContractEvent<
      MevModuleDisabledEvent.InputTuple,
      MevModuleDisabledEvent.OutputTuple,
      MevModuleDisabledEvent.OutputObject
    >;
    MevModuleDisabled: TypedContractEvent<
      MevModuleDisabledEvent.InputTuple,
      MevModuleDisabledEvent.OutputTuple,
      MevModuleDisabledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolCreatedFactory(address,address,bytes32,int24,int24,address,address)": TypedContractEvent<
      PoolCreatedFactoryEvent.InputTuple,
      PoolCreatedFactoryEvent.OutputTuple,
      PoolCreatedFactoryEvent.OutputObject
    >;
    PoolCreatedFactory: TypedContractEvent<
      PoolCreatedFactoryEvent.InputTuple,
      PoolCreatedFactoryEvent.OutputTuple,
      PoolCreatedFactoryEvent.OutputObject
    >;

    "PoolInitialized(bytes32,address,address)": TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;
    PoolInitialized: TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;

    "ProtocolFeeUpdated(uint24)": TypedContractEvent<
      ProtocolFeeUpdatedEvent.InputTuple,
      ProtocolFeeUpdatedEvent.OutputTuple,
      ProtocolFeeUpdatedEvent.OutputObject
    >;
    ProtocolFeeUpdated: TypedContractEvent<
      ProtocolFeeUpdatedEvent.InputTuple,
      ProtocolFeeUpdatedEvent.OutputTuple,
      ProtocolFeeUpdatedEvent.OutputObject
    >;

    "SocialNetworkFeeCollected(bytes32,uint256)": TypedContractEvent<
      SocialNetworkFeeCollectedEvent.InputTuple,
      SocialNetworkFeeCollectedEvent.OutputTuple,
      SocialNetworkFeeCollectedEvent.OutputObject
    >;
    SocialNetworkFeeCollected: TypedContractEvent<
      SocialNetworkFeeCollectedEvent.InputTuple,
      SocialNetworkFeeCollectedEvent.OutputTuple,
      SocialNetworkFeeCollectedEvent.OutputObject
    >;

    "SocialNetworkFundUpdated(address)": TypedContractEvent<
      SocialNetworkFundUpdatedEvent.InputTuple,
      SocialNetworkFundUpdatedEvent.OutputTuple,
      SocialNetworkFundUpdatedEvent.OutputObject
    >;
    SocialNetworkFundUpdated: TypedContractEvent<
      SocialNetworkFundUpdatedEvent.InputTuple,
      SocialNetworkFundUpdatedEvent.OutputTuple,
      SocialNetworkFundUpdatedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
