/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FeeSplitterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "BUILDER_CUT_BPS"
      | "REMAINING_BPS"
      | "SOCIAL_NETWORK_CUT_BPS"
      | "batchSetTokenFeeSplit"
      | "builderRewardDistributor"
      | "feeLocker"
      | "getTokenFeeSplit"
      | "owner"
      | "renounceOwnership"
      | "setBuilderRewardDistributor"
      | "setFeeLocker"
      | "setSocialNetworkFund"
      | "setTokenDevAddress"
      | "setTokenFeeSplit"
      | "socialNetworkFund"
      | "splitFees"
      | "tokenDevAddress"
      | "tokenFeeSplit"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BuilderRewardDistributorUpdated"
      | "BuilderRewardsDistributed"
      | "FeeLockerUpdated"
      | "FeesSplit"
      | "OwnershipTransferred"
      | "SocialNetworkFundUpdated"
      | "StakerRewardsDistributed"
      | "TokenDevAddressUpdated"
      | "TokenDevRewardsDistributed"
      | "TokenFeeSplitUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BUILDER_CUT_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REMAINING_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOCIAL_NETWORK_CUT_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetTokenFeeSplit",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "builderRewardDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feeLocker", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTokenFeeSplit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBuilderRewardDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeLocker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSocialNetworkFund",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenDevAddress",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenFeeSplit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "socialNetworkFund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "splitFees",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenDevAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenFeeSplit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BUILDER_CUT_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REMAINING_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOCIAL_NETWORK_CUT_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSetTokenFeeSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "builderRewardDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeLocker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenFeeSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBuilderRewardDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeLocker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSocialNetworkFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenDevAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenFeeSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "socialNetworkFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "splitFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenDevAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenFeeSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BuilderRewardDistributorUpdatedEvent {
  export type InputTuple = [
    oldDistributor: AddressLike,
    newDistributor: AddressLike
  ];
  export type OutputTuple = [oldDistributor: string, newDistributor: string];
  export interface OutputObject {
    oldDistributor: string;
    newDistributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuilderRewardsDistributedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeLockerUpdatedEvent {
  export type InputTuple = [oldLocker: AddressLike, newLocker: AddressLike];
  export type OutputTuple = [oldLocker: string, newLocker: string];
  export interface OutputObject {
    oldLocker: string;
    newLocker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesSplitEvent {
  export type InputTuple = [
    token: AddressLike,
    totalFees: BigNumberish,
    builderCut: BigNumberish,
    tokenDevShare: BigNumberish,
    stakerShare: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    totalFees: bigint,
    builderCut: bigint,
    tokenDevShare: bigint,
    stakerShare: bigint
  ];
  export interface OutputObject {
    token: string;
    totalFees: bigint;
    builderCut: bigint;
    tokenDevShare: bigint;
    stakerShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SocialNetworkFundUpdatedEvent {
  export type InputTuple = [oldFund: AddressLike, newFund: AddressLike];
  export type OutputTuple = [oldFund: string, newFund: string];
  export interface OutputObject {
    oldFund: string;
    newFund: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakerRewardsDistributedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenDevAddressUpdatedEvent {
  export type InputTuple = [token: AddressLike, devAddress: AddressLike];
  export type OutputTuple = [token: string, devAddress: string];
  export interface OutputObject {
    token: string;
    devAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenDevRewardsDistributedEvent {
  export type InputTuple = [
    token: AddressLike,
    dev: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, dev: string, amount: bigint];
  export interface OutputObject {
    token: string;
    dev: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenFeeSplitUpdatedEvent {
  export type InputTuple = [token: AddressLike, stakerShareBps: BigNumberish];
  export type OutputTuple = [token: string, stakerShareBps: bigint];
  export interface OutputObject {
    token: string;
    stakerShareBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FeeSplitter extends BaseContract {
  connect(runner?: ContractRunner | null): FeeSplitter;
  waitForDeployment(): Promise<this>;

  interface: FeeSplitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  BUILDER_CUT_BPS: TypedContractMethod<[], [bigint], "view">;

  REMAINING_BPS: TypedContractMethod<[], [bigint], "view">;

  SOCIAL_NETWORK_CUT_BPS: TypedContractMethod<[], [bigint], "view">;

  batchSetTokenFeeSplit: TypedContractMethod<
    [tokens: AddressLike[], stakerShareBpsArray: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  builderRewardDistributor: TypedContractMethod<[], [string], "view">;

  feeLocker: TypedContractMethod<[], [string], "view">;

  getTokenFeeSplit: TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { stakerShareBps: bigint; tokenDevShareBps: bigint }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBuilderRewardDistributor: TypedContractMethod<
    [newDistributor: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeLocker: TypedContractMethod<
    [newLocker: AddressLike],
    [void],
    "nonpayable"
  >;

  setSocialNetworkFund: TypedContractMethod<
    [newFund: AddressLike],
    [void],
    "nonpayable"
  >;

  setTokenDevAddress: TypedContractMethod<
    [token: AddressLike, devAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setTokenFeeSplit: TypedContractMethod<
    [token: AddressLike, stakerShareBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  socialNetworkFund: TypedContractMethod<[], [string], "view">;

  splitFees: TypedContractMethod<
    [token: AddressLike, totalFees: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenDevAddress: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  tokenFeeSplit: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BUILDER_CUT_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REMAINING_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SOCIAL_NETWORK_CUT_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchSetTokenFeeSplit"
  ): TypedContractMethod<
    [tokens: AddressLike[], stakerShareBpsArray: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "builderRewardDistributor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeLocker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenFeeSplit"
  ): TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { stakerShareBps: bigint; tokenDevShareBps: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBuilderRewardDistributor"
  ): TypedContractMethod<[newDistributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeLocker"
  ): TypedContractMethod<[newLocker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSocialNetworkFund"
  ): TypedContractMethod<[newFund: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenDevAddress"
  ): TypedContractMethod<
    [token: AddressLike, devAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenFeeSplit"
  ): TypedContractMethod<
    [token: AddressLike, stakerShareBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "socialNetworkFund"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "splitFees"
  ): TypedContractMethod<
    [token: AddressLike, totalFees: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenDevAddress"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "tokenFeeSplit"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BuilderRewardDistributorUpdated"
  ): TypedContractEvent<
    BuilderRewardDistributorUpdatedEvent.InputTuple,
    BuilderRewardDistributorUpdatedEvent.OutputTuple,
    BuilderRewardDistributorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BuilderRewardsDistributed"
  ): TypedContractEvent<
    BuilderRewardsDistributedEvent.InputTuple,
    BuilderRewardsDistributedEvent.OutputTuple,
    BuilderRewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "FeeLockerUpdated"
  ): TypedContractEvent<
    FeeLockerUpdatedEvent.InputTuple,
    FeeLockerUpdatedEvent.OutputTuple,
    FeeLockerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeesSplit"
  ): TypedContractEvent<
    FeesSplitEvent.InputTuple,
    FeesSplitEvent.OutputTuple,
    FeesSplitEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SocialNetworkFundUpdated"
  ): TypedContractEvent<
    SocialNetworkFundUpdatedEvent.InputTuple,
    SocialNetworkFundUpdatedEvent.OutputTuple,
    SocialNetworkFundUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StakerRewardsDistributed"
  ): TypedContractEvent<
    StakerRewardsDistributedEvent.InputTuple,
    StakerRewardsDistributedEvent.OutputTuple,
    StakerRewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "TokenDevAddressUpdated"
  ): TypedContractEvent<
    TokenDevAddressUpdatedEvent.InputTuple,
    TokenDevAddressUpdatedEvent.OutputTuple,
    TokenDevAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenDevRewardsDistributed"
  ): TypedContractEvent<
    TokenDevRewardsDistributedEvent.InputTuple,
    TokenDevRewardsDistributedEvent.OutputTuple,
    TokenDevRewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "TokenFeeSplitUpdated"
  ): TypedContractEvent<
    TokenFeeSplitUpdatedEvent.InputTuple,
    TokenFeeSplitUpdatedEvent.OutputTuple,
    TokenFeeSplitUpdatedEvent.OutputObject
  >;

  filters: {
    "BuilderRewardDistributorUpdated(address,address)": TypedContractEvent<
      BuilderRewardDistributorUpdatedEvent.InputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputObject
    >;
    BuilderRewardDistributorUpdated: TypedContractEvent<
      BuilderRewardDistributorUpdatedEvent.InputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputObject
    >;

    "BuilderRewardsDistributed(address,uint256)": TypedContractEvent<
      BuilderRewardsDistributedEvent.InputTuple,
      BuilderRewardsDistributedEvent.OutputTuple,
      BuilderRewardsDistributedEvent.OutputObject
    >;
    BuilderRewardsDistributed: TypedContractEvent<
      BuilderRewardsDistributedEvent.InputTuple,
      BuilderRewardsDistributedEvent.OutputTuple,
      BuilderRewardsDistributedEvent.OutputObject
    >;

    "FeeLockerUpdated(address,address)": TypedContractEvent<
      FeeLockerUpdatedEvent.InputTuple,
      FeeLockerUpdatedEvent.OutputTuple,
      FeeLockerUpdatedEvent.OutputObject
    >;
    FeeLockerUpdated: TypedContractEvent<
      FeeLockerUpdatedEvent.InputTuple,
      FeeLockerUpdatedEvent.OutputTuple,
      FeeLockerUpdatedEvent.OutputObject
    >;

    "FeesSplit(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FeesSplitEvent.InputTuple,
      FeesSplitEvent.OutputTuple,
      FeesSplitEvent.OutputObject
    >;
    FeesSplit: TypedContractEvent<
      FeesSplitEvent.InputTuple,
      FeesSplitEvent.OutputTuple,
      FeesSplitEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SocialNetworkFundUpdated(address,address)": TypedContractEvent<
      SocialNetworkFundUpdatedEvent.InputTuple,
      SocialNetworkFundUpdatedEvent.OutputTuple,
      SocialNetworkFundUpdatedEvent.OutputObject
    >;
    SocialNetworkFundUpdated: TypedContractEvent<
      SocialNetworkFundUpdatedEvent.InputTuple,
      SocialNetworkFundUpdatedEvent.OutputTuple,
      SocialNetworkFundUpdatedEvent.OutputObject
    >;

    "StakerRewardsDistributed(address,uint256)": TypedContractEvent<
      StakerRewardsDistributedEvent.InputTuple,
      StakerRewardsDistributedEvent.OutputTuple,
      StakerRewardsDistributedEvent.OutputObject
    >;
    StakerRewardsDistributed: TypedContractEvent<
      StakerRewardsDistributedEvent.InputTuple,
      StakerRewardsDistributedEvent.OutputTuple,
      StakerRewardsDistributedEvent.OutputObject
    >;

    "TokenDevAddressUpdated(address,address)": TypedContractEvent<
      TokenDevAddressUpdatedEvent.InputTuple,
      TokenDevAddressUpdatedEvent.OutputTuple,
      TokenDevAddressUpdatedEvent.OutputObject
    >;
    TokenDevAddressUpdated: TypedContractEvent<
      TokenDevAddressUpdatedEvent.InputTuple,
      TokenDevAddressUpdatedEvent.OutputTuple,
      TokenDevAddressUpdatedEvent.OutputObject
    >;

    "TokenDevRewardsDistributed(address,address,uint256)": TypedContractEvent<
      TokenDevRewardsDistributedEvent.InputTuple,
      TokenDevRewardsDistributedEvent.OutputTuple,
      TokenDevRewardsDistributedEvent.OutputObject
    >;
    TokenDevRewardsDistributed: TypedContractEvent<
      TokenDevRewardsDistributedEvent.InputTuple,
      TokenDevRewardsDistributedEvent.OutputTuple,
      TokenDevRewardsDistributedEvent.OutputObject
    >;

    "TokenFeeSplitUpdated(address,uint256)": TypedContractEvent<
      TokenFeeSplitUpdatedEvent.InputTuple,
      TokenFeeSplitUpdatedEvent.OutputTuple,
      TokenFeeSplitUpdatedEvent.OutputObject
    >;
    TokenFeeSplitUpdated: TypedContractEvent<
      TokenFeeSplitUpdatedEvent.InputTuple,
      TokenFeeSplitUpdatedEvent.OutputTuple,
      TokenFeeSplitUpdatedEvent.OutputObject
    >;
  };
}
