/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IBuilderRewardDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimRewards"
      | "depositRewards"
      | "distributeDailyRewards"
      | "getAvailableRewards"
      | "getContributorActiveScore"
      | "registerContribution"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContributionRegistered"
      | "ContributorScoreUpdated"
      | "DailyRewardsDistributed"
      | "RewardDeposited"
      | "RewardsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeDailyRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorActiveScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerContribution",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeDailyRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorActiveScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerContribution",
    data: BytesLike
  ): Result;
}

export namespace ContributionRegisteredEvent {
  export type InputTuple = [
    contributor: AddressLike,
    score: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contributor: string,
    score: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    contributor: string;
    score: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributorScoreUpdatedEvent {
  export type InputTuple = [contributor: AddressLike, newScore: BigNumberish];
  export type OutputTuple = [contributor: string, newScore: bigint];
  export interface OutputObject {
    contributor: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyRewardsDistributedEvent {
  export type InputTuple = [
    totalDistributed: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [totalDistributed: bigint, timestamp: bigint];
  export interface OutputObject {
    totalDistributed: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDepositedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [contributor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [contributor: string, amount: bigint];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IBuilderRewardDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): IBuilderRewardDistributor;
  waitForDeployment(): Promise<this>;

  interface: IBuilderRewardDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimRewards: TypedContractMethod<
    [contributor: AddressLike],
    [void],
    "nonpayable"
  >;

  depositRewards: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeDailyRewards: TypedContractMethod<[], [void], "nonpayable">;

  getAvailableRewards: TypedContractMethod<
    [contributor: AddressLike],
    [bigint],
    "view"
  >;

  getContributorActiveScore: TypedContractMethod<
    [contributor: AddressLike],
    [bigint],
    "view"
  >;

  registerContribution: TypedContractMethod<
    [contributor: AddressLike, score: BigNumberish, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[contributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositRewards"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeDailyRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAvailableRewards"
  ): TypedContractMethod<[contributor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContributorActiveScore"
  ): TypedContractMethod<[contributor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerContribution"
  ): TypedContractMethod<
    [contributor: AddressLike, score: BigNumberish, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ContributionRegistered"
  ): TypedContractEvent<
    ContributionRegisteredEvent.InputTuple,
    ContributionRegisteredEvent.OutputTuple,
    ContributionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ContributorScoreUpdated"
  ): TypedContractEvent<
    ContributorScoreUpdatedEvent.InputTuple,
    ContributorScoreUpdatedEvent.OutputTuple,
    ContributorScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DailyRewardsDistributed"
  ): TypedContractEvent<
    DailyRewardsDistributedEvent.InputTuple,
    DailyRewardsDistributedEvent.OutputTuple,
    DailyRewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "RewardDeposited"
  ): TypedContractEvent<
    RewardDepositedEvent.InputTuple,
    RewardDepositedEvent.OutputTuple,
    RewardDepositedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;

  filters: {
    "ContributionRegistered(address,uint256,uint256)": TypedContractEvent<
      ContributionRegisteredEvent.InputTuple,
      ContributionRegisteredEvent.OutputTuple,
      ContributionRegisteredEvent.OutputObject
    >;
    ContributionRegistered: TypedContractEvent<
      ContributionRegisteredEvent.InputTuple,
      ContributionRegisteredEvent.OutputTuple,
      ContributionRegisteredEvent.OutputObject
    >;

    "ContributorScoreUpdated(address,uint256)": TypedContractEvent<
      ContributorScoreUpdatedEvent.InputTuple,
      ContributorScoreUpdatedEvent.OutputTuple,
      ContributorScoreUpdatedEvent.OutputObject
    >;
    ContributorScoreUpdated: TypedContractEvent<
      ContributorScoreUpdatedEvent.InputTuple,
      ContributorScoreUpdatedEvent.OutputTuple,
      ContributorScoreUpdatedEvent.OutputObject
    >;

    "DailyRewardsDistributed(uint256,uint256)": TypedContractEvent<
      DailyRewardsDistributedEvent.InputTuple,
      DailyRewardsDistributedEvent.OutputTuple,
      DailyRewardsDistributedEvent.OutputObject
    >;
    DailyRewardsDistributed: TypedContractEvent<
      DailyRewardsDistributedEvent.InputTuple,
      DailyRewardsDistributedEvent.OutputTuple,
      DailyRewardsDistributedEvent.OutputObject
    >;

    "RewardDeposited(address,uint256)": TypedContractEvent<
      RewardDepositedEvent.InputTuple,
      RewardDepositedEvent.OutputTuple,
      RewardDepositedEvent.OutputObject
    >;
    RewardDeposited: TypedContractEvent<
      RewardDepositedEvent.InputTuple,
      RewardDepositedEvent.OutputTuple,
      RewardDepositedEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
  };
}
