/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IContributionRegistry {
  export type ContributionStruct = {
    contributionHash: BytesLike;
    prUrl: string;
    score: BigNumberish;
    timestamp: BigNumberish;
    contributionType: BigNumberish;
  };

  export type ContributionStructOutput = [
    contributionHash: string,
    prUrl: string,
    score: bigint,
    timestamp: bigint,
    contributionType: bigint
  ] & {
    contributionHash: string;
    prUrl: string;
    score: bigint;
    timestamp: bigint;
    contributionType: bigint;
  };
}

export interface IContributionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getContribution"
      | "getContributorInfo"
      | "recordContribution"
      | "setBuilderRewardDistributor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BuilderRewardDistributorUpdated"
      | "ContributionRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getContribution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordContribution",
    values: [
      AddressLike,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setBuilderRewardDistributor",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBuilderRewardDistributor",
    data: BytesLike
  ): Result;
}

export namespace BuilderRewardDistributorUpdatedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionRecordedEvent {
  export type InputTuple = [
    contributor: AddressLike,
    contributionHash: BytesLike,
    prUrl: string,
    score: BigNumberish,
    timestamp: BigNumberish,
    contributionType: BigNumberish
  ];
  export type OutputTuple = [
    contributor: string,
    contributionHash: string,
    prUrl: string,
    score: bigint,
    timestamp: bigint,
    contributionType: bigint
  ];
  export interface OutputObject {
    contributor: string;
    contributionHash: string;
    prUrl: string;
    score: bigint;
    timestamp: bigint;
    contributionType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IContributionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IContributionRegistry;
  waitForDeployment(): Promise<this>;

  interface: IContributionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getContribution: TypedContractMethod<
    [contributionHash: BytesLike],
    [IContributionRegistry.ContributionStructOutput],
    "view"
  >;

  getContributorInfo: TypedContractMethod<
    [contributor: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalScore: bigint;
        lastContributionTimestamp: bigint;
        contributionCount: bigint;
      }
    ],
    "view"
  >;

  recordContribution: TypedContractMethod<
    [
      contributor: AddressLike,
      contributionHash: BytesLike,
      prUrl: string,
      score: BigNumberish,
      timestamp: BigNumberish,
      contributionType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setBuilderRewardDistributor: TypedContractMethod<
    [_builderRewardDistributor: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getContribution"
  ): TypedContractMethod<
    [contributionHash: BytesLike],
    [IContributionRegistry.ContributionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContributorInfo"
  ): TypedContractMethod<
    [contributor: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalScore: bigint;
        lastContributionTimestamp: bigint;
        contributionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordContribution"
  ): TypedContractMethod<
    [
      contributor: AddressLike,
      contributionHash: BytesLike,
      prUrl: string,
      score: BigNumberish,
      timestamp: BigNumberish,
      contributionType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBuilderRewardDistributor"
  ): TypedContractMethod<
    [_builderRewardDistributor: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BuilderRewardDistributorUpdated"
  ): TypedContractEvent<
    BuilderRewardDistributorUpdatedEvent.InputTuple,
    BuilderRewardDistributorUpdatedEvent.OutputTuple,
    BuilderRewardDistributorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionRecorded"
  ): TypedContractEvent<
    ContributionRecordedEvent.InputTuple,
    ContributionRecordedEvent.OutputTuple,
    ContributionRecordedEvent.OutputObject
  >;

  filters: {
    "BuilderRewardDistributorUpdated(address)": TypedContractEvent<
      BuilderRewardDistributorUpdatedEvent.InputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputObject
    >;
    BuilderRewardDistributorUpdated: TypedContractEvent<
      BuilderRewardDistributorUpdatedEvent.InputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputTuple,
      BuilderRewardDistributorUpdatedEvent.OutputObject
    >;

    "ContributionRecorded(address,bytes32,string,uint256,uint256,uint8)": TypedContractEvent<
      ContributionRecordedEvent.InputTuple,
      ContributionRecordedEvent.OutputTuple,
      ContributionRecordedEvent.OutputObject
    >;
    ContributionRecorded: TypedContractEvent<
      ContributionRecordedEvent.InputTuple,
      ContributionRecordedEvent.OutputTuple,
      ContributionRecordedEvent.OutputObject
    >;
  };
}
