/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type PoolKeyStruct = {
  currency0: AddressLike;
  currency1: AddressLike;
  fee: BigNumberish;
  tickSpacing: BigNumberish;
  hooks: AddressLike;
};

export type PoolKeyStructOutput = [
  currency0: string,
  currency1: string,
  fee: bigint,
  tickSpacing: bigint,
  hooks: string
] & {
  currency0: string;
  currency1: string;
  fee: bigint;
  tickSpacing: bigint;
  hooks: string;
};

export declare namespace IDaemonHook {
  export type PoolConfigStruct = {
    feyIsToken0: boolean;
    locker: AddressLike;
    mevModule: AddressLike;
    mevModuleEnabled: boolean;
    feyFee: BigNumberish;
    pairedFee: BigNumberish;
    poolExtension: AddressLike;
    poolExtensionSetup: boolean;
    poolCreationTimestamp: BigNumberish;
    tokenAdmin: AddressLike;
  };

  export type PoolConfigStructOutput = [
    feyIsToken0: boolean,
    locker: string,
    mevModule: string,
    mevModuleEnabled: boolean,
    feyFee: bigint,
    pairedFee: bigint,
    poolExtension: string,
    poolExtensionSetup: boolean,
    poolCreationTimestamp: bigint,
    tokenAdmin: string
  ] & {
    feyIsToken0: boolean;
    locker: string;
    mevModule: string;
    mevModuleEnabled: boolean;
    feyFee: bigint;
    pairedFee: bigint;
    poolExtension: string;
    poolExtensionSetup: boolean;
    poolCreationTimestamp: bigint;
    tokenAdmin: string;
  };
}

export interface IDaemonHookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_LP_FEE"
      | "MAX_MEV_LP_FEE"
      | "MAX_MEV_MODULE_DELAY"
      | "PROTOCOL_FEE_NUMERATOR"
      | "baseToken"
      | "builderRewardDistributor"
      | "feeSplitter"
      | "getPoolConfig"
      | "getTokenAdmin"
      | "initializePool"
      | "poolExists"
      | "poolTokenAdmin"
      | "protocolFee"
      | "weth"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MAX_LP_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_MEV_LP_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_MEV_MODULE_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_NUMERATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "baseToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "builderRewardDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeSplitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolConfig",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializePool",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "poolExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolTokenAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;

  decodeFunctionResult(functionFragment: "MAX_LP_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_MEV_LP_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_MEV_MODULE_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_NUMERATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "builderRewardDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeSplitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolTokenAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
}

export interface IDaemonHook extends BaseContract {
  connect(runner?: ContractRunner | null): IDaemonHook;
  waitForDeployment(): Promise<this>;

  interface: IDaemonHookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_LP_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_MEV_LP_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_MEV_MODULE_DELAY: TypedContractMethod<[], [bigint], "view">;

  PROTOCOL_FEE_NUMERATOR: TypedContractMethod<[], [bigint], "view">;

  baseToken: TypedContractMethod<[], [string], "view">;

  builderRewardDistributor: TypedContractMethod<[], [string], "view">;

  feeSplitter: TypedContractMethod<[], [string], "view">;

  getPoolConfig: TypedContractMethod<
    [poolId: BytesLike],
    [IDaemonHook.PoolConfigStructOutput],
    "view"
  >;

  getTokenAdmin: TypedContractMethod<[poolId: BytesLike], [string], "view">;

  initializePool: TypedContractMethod<
    [
      fey: AddressLike,
      pairedToken: AddressLike,
      tickIfToken0IsFey: BigNumberish,
      tickSpacing: BigNumberish,
      locker: AddressLike,
      mevModule: AddressLike,
      poolData: BytesLike
    ],
    [PoolKeyStructOutput],
    "nonpayable"
  >;

  poolExists: TypedContractMethod<[poolId: BytesLike], [boolean], "view">;

  poolTokenAdmin: TypedContractMethod<[poolId: BytesLike], [string], "view">;

  protocolFee: TypedContractMethod<[], [bigint], "view">;

  weth: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_LP_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_MEV_LP_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_MEV_MODULE_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_FEE_NUMERATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "builderRewardDistributor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeSplitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolConfig"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [IDaemonHook.PoolConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenAdmin"
  ): TypedContractMethod<[poolId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "initializePool"
  ): TypedContractMethod<
    [
      fey: AddressLike,
      pairedToken: AddressLike,
      tickIfToken0IsFey: BigNumberish,
      tickSpacing: BigNumberish,
      locker: AddressLike,
      mevModule: AddressLike,
      poolData: BytesLike
    ],
    [PoolKeyStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "poolExists"
  ): TypedContractMethod<[poolId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "poolTokenAdmin"
  ): TypedContractMethod<[poolId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "weth"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
