/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSigningKey"
      | "fidExists"
      | "fidOf"
      | "getFID"
      | "getSigningKeys"
      | "nextFID"
      | "ownerOf"
      | "register"
      | "signingKeys"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FIDRegistered" | "SigningKeyAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSigningKey",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fidExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fidOf", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "getFID", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getSigningKeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextFID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "register", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "signingKeys",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addSigningKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fidExists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fidOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSigningKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextFID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "signingKeys",
    data: BytesLike
  ): Result;
}

export namespace FIDRegisteredEvent {
  export type InputTuple = [wallet: AddressLike, fid: BigNumberish];
  export type OutputTuple = [wallet: string, fid: bigint];
  export interface OutputObject {
    wallet: string;
    fid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SigningKeyAddedEvent {
  export type InputTuple = [fid: BigNumberish, key: BytesLike];
  export type OutputTuple = [fid: bigint, key: string];
  export interface OutputObject {
    fid: bigint;
    key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSigningKey: TypedContractMethod<
    [fid: BigNumberish, key: BytesLike],
    [void],
    "nonpayable"
  >;

  fidExists: TypedContractMethod<[fid: BigNumberish], [boolean], "view">;

  fidOf: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFID: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  getSigningKeys: TypedContractMethod<[fid: BigNumberish], [string[]], "view">;

  nextFID: TypedContractMethod<[], [bigint], "view">;

  ownerOf: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  register: TypedContractMethod<[], [bigint], "nonpayable">;

  signingKeys: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSigningKey"
  ): TypedContractMethod<
    [fid: BigNumberish, key: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fidExists"
  ): TypedContractMethod<[fid: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "fidOf"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFID"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSigningKeys"
  ): TypedContractMethod<[fid: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "nextFID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "signingKeys"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "FIDRegistered"
  ): TypedContractEvent<
    FIDRegisteredEvent.InputTuple,
    FIDRegisteredEvent.OutputTuple,
    FIDRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SigningKeyAdded"
  ): TypedContractEvent<
    SigningKeyAddedEvent.InputTuple,
    SigningKeyAddedEvent.OutputTuple,
    SigningKeyAddedEvent.OutputObject
  >;

  filters: {
    "FIDRegistered(address,uint256)": TypedContractEvent<
      FIDRegisteredEvent.InputTuple,
      FIDRegisteredEvent.OutputTuple,
      FIDRegisteredEvent.OutputObject
    >;
    FIDRegistered: TypedContractEvent<
      FIDRegisteredEvent.InputTuple,
      FIDRegisteredEvent.OutputTuple,
      FIDRegisteredEvent.OutputObject
    >;

    "SigningKeyAdded(uint256,bytes32)": TypedContractEvent<
      SigningKeyAddedEvent.InputTuple,
      SigningKeyAddedEvent.OutputTuple,
      SigningKeyAddedEvent.OutputObject
    >;
    SigningKeyAdded: TypedContractEvent<
      SigningKeyAddedEvent.InputTuple,
      SigningKeyAddedEvent.OutputTuple,
      SigningKeyAddedEvent.OutputObject
    >;
  };
}
