/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IdRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fidExists"
      | "fidOf"
      | "getFID"
      | "nextFID"
      | "ownerOf"
      | "recover"
      | "recoveryOf"
      | "register"
      | "setRecoveryAddress"
      | "transfer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FIDRecovered"
      | "FIDRegistered"
      | "FIDTransferred"
      | "RecoveryAddressSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "fidExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fidOf", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "getFID", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "nextFID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recover",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoveryOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "register", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setRecoveryAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "fidExists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fidOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextFID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recover", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recoveryOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRecoveryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
}

export namespace FIDRecoveredEvent {
  export type InputTuple = [
    fid: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [fid: bigint, from: string, to: string];
  export interface OutputObject {
    fid: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FIDRegisteredEvent {
  export type InputTuple = [wallet: AddressLike, fid: BigNumberish];
  export type OutputTuple = [wallet: string, fid: bigint];
  export interface OutputObject {
    wallet: string;
    fid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FIDTransferredEvent {
  export type InputTuple = [
    fid: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [fid: bigint, from: string, to: string];
  export interface OutputObject {
    fid: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryAddressSetEvent {
  export type InputTuple = [fid: BigNumberish, recovery: AddressLike];
  export type OutputTuple = [fid: bigint, recovery: string];
  export interface OutputObject {
    fid: bigint;
    recovery: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IdRegistry;
  waitForDeployment(): Promise<this>;

  interface: IdRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fidExists: TypedContractMethod<[fid: BigNumberish], [boolean], "view">;

  fidOf: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFID: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  nextFID: TypedContractMethod<[], [bigint], "view">;

  ownerOf: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  recover: TypedContractMethod<
    [fid: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  recoveryOf: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  register: TypedContractMethod<[], [bigint], "nonpayable">;

  setRecoveryAddress: TypedContractMethod<
    [recovery: AddressLike],
    [void],
    "nonpayable"
  >;

  transfer: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fidExists"
  ): TypedContractMethod<[fid: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "fidOf"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFID"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextFID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "recover"
  ): TypedContractMethod<
    [fid: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recoveryOf"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "setRecoveryAddress"
  ): TypedContractMethod<[recovery: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FIDRecovered"
  ): TypedContractEvent<
    FIDRecoveredEvent.InputTuple,
    FIDRecoveredEvent.OutputTuple,
    FIDRecoveredEvent.OutputObject
  >;
  getEvent(
    key: "FIDRegistered"
  ): TypedContractEvent<
    FIDRegisteredEvent.InputTuple,
    FIDRegisteredEvent.OutputTuple,
    FIDRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "FIDTransferred"
  ): TypedContractEvent<
    FIDTransferredEvent.InputTuple,
    FIDTransferredEvent.OutputTuple,
    FIDTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryAddressSet"
  ): TypedContractEvent<
    RecoveryAddressSetEvent.InputTuple,
    RecoveryAddressSetEvent.OutputTuple,
    RecoveryAddressSetEvent.OutputObject
  >;

  filters: {
    "FIDRecovered(uint256,address,address)": TypedContractEvent<
      FIDRecoveredEvent.InputTuple,
      FIDRecoveredEvent.OutputTuple,
      FIDRecoveredEvent.OutputObject
    >;
    FIDRecovered: TypedContractEvent<
      FIDRecoveredEvent.InputTuple,
      FIDRecoveredEvent.OutputTuple,
      FIDRecoveredEvent.OutputObject
    >;

    "FIDRegistered(address,uint256)": TypedContractEvent<
      FIDRegisteredEvent.InputTuple,
      FIDRegisteredEvent.OutputTuple,
      FIDRegisteredEvent.OutputObject
    >;
    FIDRegistered: TypedContractEvent<
      FIDRegisteredEvent.InputTuple,
      FIDRegisteredEvent.OutputTuple,
      FIDRegisteredEvent.OutputObject
    >;

    "FIDTransferred(uint256,address,address)": TypedContractEvent<
      FIDTransferredEvent.InputTuple,
      FIDTransferredEvent.OutputTuple,
      FIDTransferredEvent.OutputObject
    >;
    FIDTransferred: TypedContractEvent<
      FIDTransferredEvent.InputTuple,
      FIDTransferredEvent.OutputTuple,
      FIDTransferredEvent.OutputObject
    >;

    "RecoveryAddressSet(uint256,address)": TypedContractEvent<
      RecoveryAddressSetEvent.InputTuple,
      RecoveryAddressSetEvent.OutputTuple,
      RecoveryAddressSetEvent.OutputObject
    >;
    RecoveryAddressSet: TypedContractEvent<
      RecoveryAddressSetEvent.InputTuple,
      RecoveryAddressSetEvent.OutputTuple,
      RecoveryAddressSetEvent.OutputObject
    >;
  };
}
