/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace KeyRegistry {
  export type KeyDataStruct = {
    key: BytesLike;
    addedAt: BigNumberish;
    expiresAt: BigNumberish;
    revoked: boolean;
  };

  export type KeyDataStructOutput = [
    key: string,
    addedAt: bigint,
    expiresAt: bigint,
    revoked: boolean
  ] & { key: string; addedAt: bigint; expiresAt: bigint; revoked: boolean };
}

export interface KeyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add"
      | "fidOfKey"
      | "getActiveKeys"
      | "getKeys"
      | "idRegistry"
      | "isValidKey"
      | "keysOf"
      | "remove"
      | "revoke"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "KeyAdded" | "KeyRemoved" | "KeyRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "add",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fidOfKey", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getActiveKeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getKeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "idRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "keysOf",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remove",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fidOfKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getKeys", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "idRegistry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isValidKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keysOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remove", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
}

export namespace KeyAddedEvent {
  export type InputTuple = [
    fid: BigNumberish,
    key: BytesLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [fid: bigint, key: string, expiresAt: bigint];
  export interface OutputObject {
    fid: bigint;
    key: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeyRemovedEvent {
  export type InputTuple = [fid: BigNumberish, key: BytesLike];
  export type OutputTuple = [fid: bigint, key: string];
  export interface OutputObject {
    fid: bigint;
    key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeyRevokedEvent {
  export type InputTuple = [fid: BigNumberish, key: BytesLike];
  export type OutputTuple = [fid: bigint, key: string];
  export interface OutputObject {
    fid: bigint;
    key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KeyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): KeyRegistry;
  waitForDeployment(): Promise<this>;

  interface: KeyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<
    [fid: BigNumberish, key: BytesLike, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  fidOfKey: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getActiveKeys: TypedContractMethod<
    [fid: BigNumberish],
    [KeyRegistry.KeyDataStructOutput[]],
    "view"
  >;

  getKeys: TypedContractMethod<
    [fid: BigNumberish],
    [KeyRegistry.KeyDataStructOutput[]],
    "view"
  >;

  idRegistry: TypedContractMethod<[], [string], "view">;

  isValidKey: TypedContractMethod<[key: BytesLike], [boolean], "view">;

  keysOf: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        key: string;
        addedAt: bigint;
        expiresAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  remove: TypedContractMethod<
    [fid: BigNumberish, keyIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  revoke: TypedContractMethod<
    [fid: BigNumberish, keyIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<
    [fid: BigNumberish, key: BytesLike, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fidOfKey"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActiveKeys"
  ): TypedContractMethod<
    [fid: BigNumberish],
    [KeyRegistry.KeyDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getKeys"
  ): TypedContractMethod<
    [fid: BigNumberish],
    [KeyRegistry.KeyDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "idRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isValidKey"
  ): TypedContractMethod<[key: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "keysOf"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        key: string;
        addedAt: bigint;
        expiresAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "remove"
  ): TypedContractMethod<
    [fid: BigNumberish, keyIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<
    [fid: BigNumberish, keyIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "KeyAdded"
  ): TypedContractEvent<
    KeyAddedEvent.InputTuple,
    KeyAddedEvent.OutputTuple,
    KeyAddedEvent.OutputObject
  >;
  getEvent(
    key: "KeyRemoved"
  ): TypedContractEvent<
    KeyRemovedEvent.InputTuple,
    KeyRemovedEvent.OutputTuple,
    KeyRemovedEvent.OutputObject
  >;
  getEvent(
    key: "KeyRevoked"
  ): TypedContractEvent<
    KeyRevokedEvent.InputTuple,
    KeyRevokedEvent.OutputTuple,
    KeyRevokedEvent.OutputObject
  >;

  filters: {
    "KeyAdded(uint256,bytes32,uint256)": TypedContractEvent<
      KeyAddedEvent.InputTuple,
      KeyAddedEvent.OutputTuple,
      KeyAddedEvent.OutputObject
    >;
    KeyAdded: TypedContractEvent<
      KeyAddedEvent.InputTuple,
      KeyAddedEvent.OutputTuple,
      KeyAddedEvent.OutputObject
    >;

    "KeyRemoved(uint256,bytes32)": TypedContractEvent<
      KeyRemovedEvent.InputTuple,
      KeyRemovedEvent.OutputTuple,
      KeyRemovedEvent.OutputObject
    >;
    KeyRemoved: TypedContractEvent<
      KeyRemovedEvent.InputTuple,
      KeyRemovedEvent.OutputTuple,
      KeyRemovedEvent.OutputObject
    >;

    "KeyRevoked(uint256,bytes32)": TypedContractEvent<
      KeyRevokedEvent.InputTuple,
      KeyRevokedEvent.OutputTuple,
      KeyRevokedEvent.OutputObject
    >;
    KeyRevoked: TypedContractEvent<
      KeyRevokedEvent.InputTuple,
      KeyRevokedEvent.OutputTuple,
      KeyRevokedEvent.OutputObject
    >;
  };
}
