/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StorageRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPrice"
      | "getStorageUnits"
      | "idRegistry"
      | "owner"
      | "pricePerUnit"
      | "rent"
      | "setPrice"
      | "setTestnetMode"
      | "storageUnitsOf"
      | "testnetMode"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PriceUpdated"
      | "StorageRented"
      | "TestnetModeUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getStorageUnits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "idRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pricePerUnit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTestnetMode",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "storageUnitsOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testnetMode",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStorageUnits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "idRegistry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pricePerUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTestnetMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storageUnitsOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testnetMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StorageRentedEvent {
  export type InputTuple = [
    fid: BigNumberish,
    units: BigNumberish,
    totalCost: BigNumberish
  ];
  export type OutputTuple = [fid: bigint, units: bigint, totalCost: bigint];
  export interface OutputObject {
    fid: bigint;
    units: bigint;
    totalCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TestnetModeUpdatedEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StorageRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): StorageRegistry;
  waitForDeployment(): Promise<this>;

  interface: StorageRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPrice: TypedContractMethod<[], [bigint], "view">;

  getStorageUnits: TypedContractMethod<[fid: BigNumberish], [bigint], "view">;

  idRegistry: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pricePerUnit: TypedContractMethod<[], [bigint], "view">;

  rent: TypedContractMethod<
    [fid: BigNumberish, units: BigNumberish],
    [void],
    "payable"
  >;

  setPrice: TypedContractMethod<[newPrice: BigNumberish], [void], "nonpayable">;

  setTestnetMode: TypedContractMethod<[enabled: boolean], [void], "nonpayable">;

  storageUnitsOf: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  testnetMode: TypedContractMethod<[], [boolean], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStorageUnits"
  ): TypedContractMethod<[fid: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "idRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pricePerUnit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rent"
  ): TypedContractMethod<
    [fid: BigNumberish, units: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<[newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTestnetMode"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "storageUnitsOf"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "testnetMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StorageRented"
  ): TypedContractEvent<
    StorageRentedEvent.InputTuple,
    StorageRentedEvent.OutputTuple,
    StorageRentedEvent.OutputObject
  >;
  getEvent(
    key: "TestnetModeUpdated"
  ): TypedContractEvent<
    TestnetModeUpdatedEvent.InputTuple,
    TestnetModeUpdatedEvent.OutputTuple,
    TestnetModeUpdatedEvent.OutputObject
  >;

  filters: {
    "PriceUpdated(uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "StorageRented(uint256,uint256,uint256)": TypedContractEvent<
      StorageRentedEvent.InputTuple,
      StorageRentedEvent.OutputTuple,
      StorageRentedEvent.OutputObject
    >;
    StorageRented: TypedContractEvent<
      StorageRentedEvent.InputTuple,
      StorageRentedEvent.OutputTuple,
      StorageRentedEvent.OutputObject
    >;

    "TestnetModeUpdated(bool)": TypedContractEvent<
      TestnetModeUpdatedEvent.InputTuple,
      TestnetModeUpdatedEvent.OutputTuple,
      TestnetModeUpdatedEvent.OutputObject
    >;
    TestnetModeUpdated: TypedContractEvent<
      TestnetModeUpdatedEvent.InputTuple,
      TestnetModeUpdatedEvent.OutputTuple,
      TestnetModeUpdatedEvent.OutputObject
    >;
  };
}
