/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TGEWrapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contributeToTGE"
      | "contributeToTGEWithToken"
      | "factory"
      | "setUseTestToken"
      | "testETHToken"
      | "useTestToken"
      | "withdrawETH"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TGEWithToken"): EventFragment;

  encodeFunctionData(
    functionFragment: "contributeToTGE",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contributeToTGEWithToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setUseTestToken",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "testETHToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "useTestToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "contributeToTGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributeToTGEWithToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUseTestToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testETHToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "useTestToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
}

export namespace TGEWithTokenEvent {
  export type InputTuple = [
    token: AddressLike,
    contributor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    contributor: string,
    amount: bigint
  ];
  export interface OutputObject {
    token: string;
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TGEWrapper extends BaseContract {
  connect(runner?: ContractRunner | null): TGEWrapper;
  waitForDeployment(): Promise<this>;

  interface: TGEWrapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contributeToTGE: TypedContractMethod<[token: AddressLike], [void], "payable">;

  contributeToTGEWithToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  factory: TypedContractMethod<[], [string], "view">;

  setUseTestToken: TypedContractMethod<
    [_useTestToken: boolean],
    [void],
    "nonpayable"
  >;

  testETHToken: TypedContractMethod<[], [string], "view">;

  useTestToken: TypedContractMethod<[], [boolean], "view">;

  withdrawETH: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contributeToTGE"
  ): TypedContractMethod<[token: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "contributeToTGEWithToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setUseTestToken"
  ): TypedContractMethod<[_useTestToken: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "testETHToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "useTestToken"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawETH"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "TGEWithToken"
  ): TypedContractEvent<
    TGEWithTokenEvent.InputTuple,
    TGEWithTokenEvent.OutputTuple,
    TGEWithTokenEvent.OutputObject
  >;

  filters: {
    "TGEWithToken(address,address,uint256)": TypedContractEvent<
      TGEWithTokenEvent.InputTuple,
      TGEWithTokenEvent.OutputTuple,
      TGEWithTokenEvent.OutputObject
    >;
    TGEWithToken: TypedContractEvent<
      TGEWithTokenEvent.InputTuple,
      TGEWithTokenEvent.OutputTuple,
      TGEWithTokenEvent.OutputObject
    >;
  };
}
