/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IBuilderRewardDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimRewards"
      | "depositRewards"
      | "distributeDailyRewards"
      | "getAvailableRewards"
      | "getContributorScore"
      | "registerContribution"
      | "updateContributorScore"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeDailyRewards",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerContribution",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContributorScore",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeDailyRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContributorScore",
    data: BytesLike
  ): Result;
}

export interface IBuilderRewardDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): IBuilderRewardDistributor;
  waitForDeployment(): Promise<this>;

  interface: IBuilderRewardDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  depositRewards: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeDailyRewards: TypedContractMethod<
    [contributors: AddressLike[], scores: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getAvailableRewards: TypedContractMethod<
    [contributor: AddressLike],
    [bigint],
    "view"
  >;

  getContributorScore: TypedContractMethod<
    [contributor: AddressLike, timestamp: BigNumberish],
    [bigint],
    "view"
  >;

  registerContribution: TypedContractMethod<
    [contributor: AddressLike, score: BigNumberish, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateContributorScore: TypedContractMethod<
    [contributor: AddressLike, scoreDelta: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositRewards"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeDailyRewards"
  ): TypedContractMethod<
    [contributors: AddressLike[], scores: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAvailableRewards"
  ): TypedContractMethod<[contributor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContributorScore"
  ): TypedContractMethod<
    [contributor: AddressLike, timestamp: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerContribution"
  ): TypedContractMethod<
    [contributor: AddressLike, score: BigNumberish, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateContributorScore"
  ): TypedContractMethod<
    [contributor: AddressLike, scoreDelta: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
